### ISSUE TITLE
number of query/reference intervals

### ISSUE THREAD

**Issue by nicotel** [shahab-sarmashghi/ISTAT#1]
Dear shahab,

I am appreciating the versatility and the speed of this tool. There is one aspect I did not completely got, why do I see a discrepancy in the number of intervals in the file in input and those printed out ? For example, your toy data file hirt_chr.txt and tcga_chr.txt contain 247 and 6521 intervals respectively but the result printed on std output is either 116 or 101 intervals.

Best Regards,

Nicolò

**Comment by shahab-sarmashghi** [comment]
Hi Nicolò,

Thank you for your question. Sorry for my late reply. Happy to hear that you find the tool useful.

The reason for the difference you see between input intervals and output intervals can be either that the intervals where originally overlapping so we merged them, or because of the scaling factor provided to the input, the intervals became adjoining after scaling so we merged them and ended up with a smaller number of intervals. This is quite dependent on the distribution of input intervals and there might be cases that the number of intervals between input and output are the same, or can be different as this case.

I hope that clarifies your question. Please let me know if you have any questions.

Bests, Shahab.
